gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
