	.align 2
gText_ConfirmSave::
	.string "Would you like to save the game?$"

gText_AlreadySavedFile::
	.string "Overwrite existing save?$"

gText_SavingDontTurnOff::
	.string "SAVING…$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "Different file. Overwrite?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
